### ISSUE TITLE
Not supporting JDK8？

### ISSUE THREAD

**Issue by OriginNull** [coekie/flowtracker#3]
Not supporting JDK8？

**Comment by coekie** [comment]
No, JDK 8 is not supported, and I don't want to add support for it. It's too old; time to upgrade.

As mentioned on https://github.com/coekie/flowtracker/blob/master/USAGE.md , Flowtracker is currently tested on JDK 11, 17, 21 and 22. (JDK 23 was released yesterday, but is only supported when building FlowTracker with `-Pexperimental`, because that requires an unreleased version of ASM).
